name: Generate Changelog

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Generate changelog
        run: |
          npm install --no-audit --no-fund
          npm run generate-changelog
      - name: Commit & push if changed
        run: |
          if git diff --quiet CHANGELOG.md; then
            echo "No changes"; exit 0; fi
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add CHANGELOG.md
            
          git commit -m "chore: auto-update CHANGELOG"
          git push
