name: Genera bollettino meteo

on:
  workflow_dispatch:  # esegui manualmente dal tab Actions

permissions:
  contents: write

jobs:
  bollettino:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # solo l'ultimo commit

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install transformers torch

      - name: Genera bollettino meteo
        run: |
          python - <<'EOF'
          import json
          from transformers import pipeline

          # Carico i dati meteo
          with open("data.json") as f:
              data = json.load(f)

          # Prendo i dati di domani
          daily = data["daily"]
          tomorrow_idx = 1  # indice 1 = domani
          giorno = daily["time"][tomorrow_idx]
          tmax = daily["temperature_2m_max"][tomorrow_idx]
          tmin = daily["temperature_2m_min"][tomorrow_idx]
          rain = daily["precipitation_sum"][tomorrow_idx]
          prob = daily["precipitation_probability_max"][tomorrow_idx]

          # Creo il prompt per il modello
          prompt = (
              f"Scrivi un bollettino meteo leggero e scherzoso per il giorno {giorno}. "
              f"La temperatura massima sarà {tmax}°C e la minima {tmin}°C. "
              f"Ci si aspetta {rain} mm di pioggia con una probabilità massima del {prob}%. "
              f"Il testo deve sembrare una simpatica previsione radiofonica."
          )

          # Carico il modello Hugging Face
          generator = pipeline("text-generation", model="distilgpt2")

          # Genero il testo
          result = generator(prompt, max_length=180, num_return_sequences=1)[0]["generated_text"]

          # Salvo su file
          with open("bollettino.txt", "w") as f:
              f.write(result)

          print("Bollettino generato in bollettino.txt")
          EOF

      - name: Bulleting dump
        run: |
          echo "Generated bulleting:"
          echo "---------------------"
          cat bollettino.txt
          echo "---------------------"
          
      - name: Commit bollettino
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: added meteo bulletin
          branch: main
          file_pattern: bollettino.txt