name: Genera bollettino meteo

on:
  workflow_dispatch:  # esegui manualmente dal tab Actions

permissions:
  contents: write

jobs:
  bollettino:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # solo l'ultimo commit

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Genera bollettino meteo
        run: |
          python3 _scripts/generate-bulletin.py

      - name: Bulletin dump
        run: |
          echo "Generated bulletin:"
          echo "---------------------"
          cat bollettino.txt
          echo "---------------------"
          
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "data: aggiorna bollettino meteo"
          branch: main
          file_pattern: bollettino.txt